@startuml
!include ../style.puml

participant ":Storage" as S STORAGE_COLOR
participant "<<Class>>\n:CaseManager" as CM CASEFILE_COLOR
participant ":Case" as C CASEFILE_COLOR

-[MAIN_COLOR]> S : saveToFile()
activate S STORAGE_COLOR_T1

S -[STORAGE_COLOR]> CM : getCaseManager
activate CM CASEFILE_COLOR_T1
return caseList
deactivate CM

loop for cases in caseList
S -[STORAGE_COLOR]> C : getSaveString()
activate C CASEFILE_COLOR_T1
return save string
deactivate C
end loop

<[MAIN_COLOR]-- S
deactivate S

@enduml