'unused, feel free to take it and use it'

@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

actor User as user USER_COLOR
participant ":SGSafe" as sgsafe MAIN_COLOR
participant ":Parser" as parser UI_COLOR
participant ":Validator" as validator UI_COLOR

user -[USER_COLOR]> sgsafe : "list &#45;&#45;mode verbose &#45;&#45;status closed"
activate sgsafe MAIN_COLOR

sgsafe -[MAIN_COLOR]> parser : parseInput("list ...")
activate parser UI_COLOR

parser -[UI_COLOR]> parser : parseListCommand(...)
activate parser

parser -[UI_COLOR]> parser : extractFlagValues(...)
activate parser
return

parser -[UI_COLOR]> validator : haveValidFlags(...)
activate validator UI_COLOR
return

parser -[UI_COLOR]> parser : parseListStatus(...)
activate parser
return

parser -[UI_COLOR]> parser : parseListMode(...)
activate parser
return

create participant ":ListCommand" as listCmd COMMAND_COLOR
parser -[UI_COLOR]> listCmd : new ListCommand(...)
activate listCmd COMMAND_COLOR

listCmd --> parser : return ListCommand
deactivate listCmd

parser --> parser : return ListCommand
deactivate parser

parser --> sgsafe : return ListCommand
deactivate parser

@enduml