@startuml

autoactivate on
!include ../style.puml

participant ":Storage" as S STORAGE_COLOR
participant ":Case" as C CASEFILE_COLOR
participant ":Parser" as P UI_COLOR

group sd initialise case

S -[STORAGE_COLOR]> P : convertFlagValueTypes()
return fields

S -[STORAGE_COLOR]> C : update(fields)
return

S -[STORAGE_COLOR]> C : setDeleted(...)
return

opt case is open
S -[STORAGE_COLOR]> C : setOpen()
return
else case is closed
S -[STORAGE_COLOR]> C : setClosed()
return
end opt

end group

@enduml