@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

actor User as user USER_COLOR
participant ":SGSafe" as sgsafe SGSAFE_COLOR
participant ":Parser" as parser PARSER_COLOR
participant ":Validator" as validator VALIDATOR_COLOR

user -[USER_COLOR]> sgsafe : "user input"
activate sgsafe SGSAFE_COLOR

sgsafe -[SGSAFE_COLOR]> parser : parseInput(...)
activate parser PARSER_COLOR

parser -[PARSER_COLOR]> parser : parseCommand(...)
activate parser

parser -[PARSER_COLOR]> parser : extractFlagValues(...)
activate parser
deactivate parser

parser -[PARSER_COLOR]> validator : haveValidFlags(...)
activate validator VALIDATOR_COLOR
deactivate validator

create participant ":Command" as newCmd COMMAND_COLOR
parser -[PARSER_COLOR]> newCmd : new Command(...)
activate newCmd COMMAND_COLOR

newCmd --> parser : return Command
deactivate newCmd

parser --> parser : return Command
deactivate parser

parser --> sgsafe : return Command
deactivate parser

@enduml