@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

participant ":SGSafe" as sgsafe MAIN_COLOR
participant ":Parser" as parser UI_COLOR

activate sgsafe MAIN_COLOR


sgsafe -[UI_COLOR]> parser : parseInput(...)
activate parser UI_COLOR

create participant ":Command" as cmd COMMAND_COLOR

parser -[UI_COLOR]> cmd : new Command(...)
activate cmd COMMAND_COLOR
cmd --[UI_COLOR]> parser : return
deactivate cmd
parser --[UI_COLOR]> sgsafe : return Command
deactivate parser

participant ":Display" as display UI_COLOR

sgsafe -[MAIN_COLOR]> cmd : execute()
activate cmd COMMAND_COLOR

cmd -[COMMAND_COLOR]> cmd : someSelfFunction()
activate cmd COMMAND_COLOR_T1
deactivate cmd

participant ":CaseManager" as caseMgr CASEFILE_COLOR
cmd -[COMMAND_COLOR]> caseMgr : perform some operation
activate caseMgr CASEFILE_COLOR

participant ":Case" as case CASEFILE_COLOR

caseMgr -[CASEFILE_COLOR]> case : perform some operation

caseMgr --[CASEFILE_COLOR]> cmd : return result

deactivate caseMgr

cmd --[UI_COLOR]> display : printDisplay(...)
activate display UI_COLOR
deactivate display


deactivate display UI_COLOR



destroy cmd

deactivate caseMgr

'note left of someSelfFunction()
'  someSelfFunction() represents any internal
'  function calls the Command might make to itself
'  during execution.
'end note
@enduml